############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Calendar"
url = "/calendar"
weight = 2


[[main]]
name = "Resources"
url = "/resources"
weight = 4

[[main]]
name = "About"
url = "/about"
weight = 10
